<a href="https://colab.research.google.com/github/parthapratimkalita/ELOBSE/blob/master/NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np #importing the numpy array as np

x = np.random.randint(0, 2, size=6) #generating a random array 'x' where lowest element can be one and highest could be 2-1.

t = [] #intializing an array t

for i in range(len(x)):
  m = x[i]**3 - x[i]**2
  t.append(m)

t = np.array(t)

print(t)

[0 0 0 0 0 0]


In [ ]:
import numpy as np

class Layers:

  def __init__(self, n_units, input_units):

    self.n_units = n_units
    self.input_units = input_units
    

    self.weights = np.random.randint(1,4, size=(self.input_units, self.n_units))
    self.biases = np.zeros(shape=(1, self.n_units), dtype= 'i')


  def Relu(self,m):

    shape = m.shape
    comp = np.zeros(shape=(1, shape[1]), dtype= 'i')
    return np.maximum(m,comp)

  def forward_step(self, input_values):

    self.input_values = input_values
    self.input_values = np.asarray(self.input_values).reshape(1,self.input_units)

    self.sum = np.dot(self.input_values, self.weights) 

 
    self.sum = self.sum + self.biases

    self.output = self.Relu(self.sum)
    return self.output


  def derivative_out_wrt_act(self, out1):

      shape = out1.shape

      for i in range(shape[1]):
          if out1[0][i] <= 0:
              out1[0][i] = 0
          else:
              out1[0][i] = 1

      return out1


  def loss(self, ta1):

    ta1 = np.array(ta1).reshape(1, len(ta1))

    #print(ta1)
    #print(self.output)
    derv_loss_wrt_out = self.output - ta1
    return derv_loss_wrt_out

  def hidden_layer_loss(self, loss1, weights):

    hid_loss = np.dot( loss1, np.transpose(weights))
    return hid_loss


  def backward_step(self, lear_rate, loss, prev):
      

      #print("@@@@")

      derv_loss_wrt_out = loss
      #print(derv_loss_wrt_out)
      derv_out_wrt_act  = self.derivative_out_wrt_act(self.sum)
      #print(derv_out_wrt_act)
      derv_input_wrt_wei = self.input_values
      #print(derv_input_wrt_wei)

      right = derv_loss_wrt_out * derv_out_wrt_act  * prev

      loss_wrt_wei = np.dot(np.transpose(derv_input_wrt_wei),  right)
      
      self.weights = self.weights - lear_rate * loss_wrt_wei

      return [right, self.weights]

    
      #return self.output


# Multi layer perceptron class with two layers

class MLP(Layers):

  Lar_h = Layers(10,1)
  Lar_out = Layers(1,10) 


#loss calculation of the network
  def end_loss(y, t):
      sq = (y-t)*(y-t)
      los = 0.5 * sq

      return los

  for i in range(10):

      for j in range(6):

# Implementing feedforward propagation on hidden layer
        out = Lar_h.forward_step([x[j]])

# Implementing feed forward propagation on output layer
        out1 = Lar_out.forward_step(out[0])



# Backpropagation phase

        # Calculating the error at output nodes
        loss = Lar_out.loss([t[j]])

        back_derv_1 = Lar_out.backward_step(0.5, loss, 1)

        
        #Calculating the error at the hidden nodes
        loss = Lar_h.hidden_layer_loss(loss, back_derv_1[1])

        back_derv_2 = Lar_h.backward_step(0.5, loss, back_derv_1[0] )















In [ ]:
class MLP(Layers):

  Lar_h = Layers(10,1)
  Lar_out = Layers(1,10)
  out = Lar_h.forward_step([x[0]])
  out1 = Lar_out.forward_step(out[0])

  print(out1)

 

[[33]]


In [ ]:
class MLP(Layers):

  Lar_h = Layers(10,1)
  Lar_out = Layers(1,10) 

  def end_loss(y, t):

      los
      sq = (y-t)*(y-t)
      los = 0.5 * sq

      return los


  if i is 0:
            target = np.array(np.zeros(6)).reshape(1, 6)
            end_los = end_loss(out1[0,0], t[j])
            target[0][j] = end_los

        else:
            target1 = np.array(np.zeros(6)).reshape(1, 6)
            end_los = end_loss(out1[0,0], t[j])
            target1[0][j] = end_los

  for i in range(2):

      for j in range(1):

        out = Lar_h.forward_step([x[j]])
        out1 = Lar_out.forward_step(out[0])

        comp_tar = np.array([]) 

        

        comp_tar = np.append(target, target1, axis = 0)
            

        loss = Lar_out.loss([t[j]])

        back_derv_1 = Lar_out.backward_step(0.5, loss, 1)

        loss = Lar_h.hidden_layer_loss(loss, back_derv_1[1])

        back_derv_2 = Lar_h.backward_step(0.5, loss, back_derv_1[0] )


  print("loss after each epoch")
  print(comp_tar)

NameError: ignored

In [ ]:
import numpy as np
target = np.zeros(6)
target = np.array(target).reshape(1, len(target))
print(target)

[[0. 0. 0. 0. 0. 0.]]


In [ ]:
import numpy as np

class Layers:

  def __init__(self, n_units, input_units):

    self.n_units = n_units
    self.input_units = input_units
    

    self.weights = np.random.randint(1,4, size=(self.input_units, self.n_units))
    self.biases = np.zeros(shape=(1,self.n_units), dtype= 'i')
    #print(self.biases)


  def Relu(self,x,y):
    return np.maximum(x,y)

  def forward_step(self, input_values):

    self.input_values = input_values
    self.input_values = np.array(self.input_values)


    #print(self.weights)
    self.sum = np.dot(self.input_values, self.weights) 

    #print(self.sum)

    self.sum = self.sum + self.biases

    #print("****")

    #print(self.sum)


    comp_relu = np.empty(shape = (1,len(self.sum)), dtype ='i')
    self.output = self.Relu(self.sum, comp_relu)

    #print(self.output)
    return self.output

  def derivative_out_wrt_act(self, out):

      self.output = out

      shape = self.output.shape

      for i in range(shape[1]):
          if self.output[0][i] <= 0:
            self.output[0][i] = 0
          else:
            self.output[0][i] = 1

      return self.output

  def backward_step(self, target, lear_rate):
    
    self.target = target
    self.learn_rate = lear_rate


    dim = self.output.shape
    unit_matrix = np.ones(dim, dtype="i")

    #print(self.weights)
    #print("******")

    derv_loss_wrt_out = self.output - self.target 
    derv_out_wrt_actv  = self.derivative_out_wrt_act(self.output)

    derv_inp_wrt_wei = np.array([self.input_values])
    #print(derv_inp_wrt_wei.shape)

    for i in range(0, 99):
      derv_inp_wrt_wei = np.append(derv_inp_wrt_wei, [self.input_values], axis=0)

    derv_inp_wrt_wei = np.transpose(derv_inp_wrt_wei)


    derv_loss_wrt_wei = derv_loss_wrt_out * derv_out_wrt_actv

    print("")
    print(derv_inp_wrt_wei)

    derv_loss_wrt_wei = derv_inp_wrt_wei * derv_loss_wrt_wei

    #print("derv_out_wrt_actv")
    #print(derv_out_wrt_actv)
    #print("derv_loss_wrt_out")
    #print(derv_loss_wrt_out)
    #print("derv_inp_wrt_wei")
    #print(derv_inp_wrt_wei)
    print("derv_loss_wrt_wei")
    print(derv_loss_wrt_wei)

    self.weights = self.weights - lear_rate * derv_loss_wrt_wei

    print("update weights")
    print(self.weights)

    



  


obj = Layers(100,100)

out = obj.forward_step(x)
wei = obj.backward_step(t, 0.5)

print("*****")

out = obj.forward_step(x)
wei = obj.backward_step(t, 0.5)

print("*****")

out = obj.forward_step(x)
wei = obj.backward_step(t, 0.5)








[[3 1 3 2 2 1 3 3 2 2]]
[[1]
 [1]
 [1]
 [3]
 [1]
 [3]
 [3]
 [1]
 [1]
 [1]]
[[3 1 3 2 2 1 3 3 2 2]]
[[34]]
derv_loss_wrt_wei1
[[34]]
derv_loss_wrt_wei
[[102 102 102 102 102 102 102 102 102 102]
 [ 34  34  34  34  34  34  34  34  34  34]
 [102 102 102 102 102 102 102 102 102 102]
 [ 68  68  68  68  68  68  68  68  68  68]
 [ 68  68  68  68  68  68  68  68  68  68]
 [ 34  34  34  34  34  34  34  34  34  34]
 [102 102 102 102 102 102 102 102 102 102]
 [102 102 102 102 102 102 102 102 102 102]
 [ 68  68  68  68  68  68  68  68  68  68]
 [ 68  68  68  68  68  68  68  68  68  68]]
@@@@@@@@@@@@@
[[1]
 [1]
 [1]
 [3]
 [1]
 [3]
 [3]
 [1]
 [1]
 [1]]
[[-50. -50. -50. -50. -50. -50. -50. -50. -50. -50.]
 [-16. -16. -16. -16. -16. -16. -16. -16. -16. -16.]
 [-50. -50. -50. -50. -50. -50. -50. -50. -50. -50.]
 [-31. -31. -31. -31. -31. -31. -31. -31. -31. -31.]
 [-33. -33. -33. -33. -33. -33. -33. -33. -33. -33.]
 [-14. -14. -14. -14. -14. -14. -14. -14. -14. -14.]
 [-48. -48. -48. -48. -48. -48. -48.

In [ ]:
derv_inp_wrt_wei = np.transpose(derv_inp_wrt_wei)


    derv_loss_wrt_wei = derv_loss_wrt_out * derv_out_wrt_actv

    print(derv_inp_wrt_wei.shape)

    derv_loss_wrt_wei = np.dot(derv_inp_wrt_wei, derv_loss_wrt_wei)

    print("derv_out_wrt_actv")
    print(derv_out_wrt_actv)
    print("derv_loss_wrt_out")
    print(derv_loss_wrt_out)
    print("derv_inp_wrt_wei")
    print(derv_inp_wrt_wei)
    print("derv_loss_wrt_wei")
    print(derv_loss_wrt_wei)

    self.weights = self.weights - lear_rate * derv_loss_wrt_wei

  
    print(self.weights)

In [ ]:
import numpy as np
x = np.array([[1,2,3]])
x = np.append(x, [[2,3,5]], axis =0)
print(x)
x = x * [2,2,2]
print(x)

[[1 2 3]
 [2 3 5]]
[[ 2  4  6]
 [ 4  6 10]]
